package dal.dao.conection;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public interface ConnectionWithRestrictedAbilities extends AutoCloseable {
    @Override
    void close() throws SQLException;
    Connection getSubject();
    PreparedStatement prepareStatement(String sql) throws SQLException;
    PreparedStatement prepareStatement(String sql, int autoGeneratedKeys)throws SQLException;
}
