package dal.handling.conection.impl;

import dal.handling.conection.ConnectionWithRestrictedAbilities;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class ConnectionAdapterToConnectionWithRestrictedAbilities implements ConnectionWithRestrictedAbilities {

    private final Connection connection;

    public ConnectionAdapterToConnectionWithRestrictedAbilities(Connection connection) {
        this.connection = connection;
    }

    @Override
    public PreparedStatement prepareStatement(String sql) throws SQLException {

        return connection.prepareStatement(sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        return connection.prepareStatement(sql, autoGeneratedKeys);
    }

    @Override
    public void close() throws SQLException {
        connection.close();
    }

    @Override
    public Connection getSubject() {
        return connection;
    }
}
